### ISSUE TITLE
Issue for frontend developer 

### ISSUE THREAD

**Issue by Ixa1** [AnitaWaiba/Collaborative#1]
![image](https://github.com/AnitaWaiba/Collaborative/assets/119478705/ea336378-a26d-4f17-941f-a20843045445)
Differentiate between the login and signup buttons by using primary and secondary buttons. Additionally, the login button in the center does not seem to match and should be replaced.

**Comment by AnitaWaiba** [comment]
![Screenshot 2024-04-10 230222](https://github.com/AnitaWaiba/Collaborative/assets/119423817/dceb82a2-bf6c-4025-8b05-4235df3e62a2)
