### ISSUE TITLE
Button Redirect from Home page

### ISSUE THREAD

**Issue by SimonMalla** [AnitaWaiba/Collaborative#2]
![issue 1](https://github.com/AnitaWaiba/Collaborative/assets/119477924/850d4ea5-2da9-4fc4-a910-1dc0c5f89b8f)
![issue 2](https://github.com/AnitaWaiba/Collaborative/assets/119477924/cea54f99-b934-4114-85ad-0ec2470f2082)
Ready to get started/Ask a question button should redirect to relevant page.

**Comment by AnitaWaiba** [comment]
![image](https://github.com/AnitaWaiba/Collaborative/assets/119423817/b409c955-32a6-4c91-968d-df1334eb14fe)
![image](https://github.com/AnitaWaiba/Collaborative/assets/119423817/c6f39854-c626-4483-81c2-7c053b47d1c6)
